# -*- coding: utf-8 -*-
"""titanic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/minsungkim0303/de4f5bb71ce031b409e5c356c8034229/titanic.ipynb
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

train = pd.read_csv("train.csv")

# EDA

train.head()

train.shape

train.describe()

# Data Description
# (from https://www.kaggle.com/c/titanic)

# survival: Survival (0 = No; 1 = Yes)
# pclass: Passenger Class (1 = 1st; 2 = 2nd; 3 = 3rd)
# name: Name
# sex: Sex
# age: Age
# sibsp: Number of Siblings/Spouses Aboard
# parch: Number of Parents/Children Aboard
# ticket: Ticket Number
# fare: Passenger Fare
# cabin: Cabin
# embarked: Port of Embarkation (C = Cherbourg; Q = Queenstown; S = Southampton)

# 결측치 제거 등 데이터 전처리 예정

